name: Deploy Cloudflare Worker

# 触发条件：每次 push 到 main 分支
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取仓库
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. 设置 Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install

      # 4. 部署 Worker
      - name: Deploy to Cloudflare
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
